<a href="https://colab.research.google.com/github/FerMendezG/AluraStore/blob/main/AluraStoreLatam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importación de datos

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

In [ ]:
type(tienda)

pandas.core.frame.DataFrame

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Silla de oficina,Muebles,283600.0,15300.0,04/08/2021,Izabela de León,Medellín,1,Nequi,1,6.25184,-75.56359
1,Pandereta,Instrumentos musicales,76800.0,2300.0,26/11/2020,Blanca Ramirez,Medellín,3,Tarjeta de crédito,4,6.25184,-75.56359
2,Cama king,Muebles,443300.0,23800.0,22/10/2021,Izabela de León,Pereira,5,Tarjeta de crédito,10,4.81333,-75.69611
3,Cama king,Muebles,906200.0,46400.0,04/05/2022,Maria Alfonso,Cali,5,Tarjeta de crédito,10,3.43722,-76.52250
4,Silla de oficina,Muebles,397800.0,19400.0,26/02/2022,Lucas Olivera,Bogotá,4,Tarjeta de crédito,3,4.60971,-74.08175

In [ ]:
Total = tienda["Precio"].sum()
Total2 = tienda2["Precio"].sum()
Total3 = tienda3["Precio"].sum()
Total4 = tienda4["Precio"].sum()
print(f'Total facturado tienda 1: $ {Total}')
print(f'Total facturado tienda 2: $ {Total2}')
print(f'Total facturado tienda 3: $ {Total3}')
print(f'Total facturado tienda 4: $ {Total4}')
Total_final = Total + Total2 + Total3 + Total4
print(f'Total geeneral por las 4 tiendas: ${Total_final}')

Total facturado tienda 1: $1150880400.0
Total facturado tienda 2: $1116343500.0
Total facturado tienda 3: $1098019600.0
Total facturado tienda 4: $1038375700.0
Total geeneral por las 4 tiendas: $4403619200.0

# 2. Ventas por categoría

In [ ]:
# ventas por categoria por tienda
ventas_por_categoria_tienda1 = tienda.groupby('Categoría del Producto')['Precio'].sum().sort_values(ascending=False)
ventas_por_categoria_tienda2 = tienda2.groupby('Categoría del Producto')['Precio'].sum().sort_values(ascending=False)
ventas_por_categoria_tienda3 = tienda3.groupby('Categoría del Producto')['Precio'].sum().sort_values(ascending=False)
ventas_por_categoria_tienda4 = tienda4.groupby('Categoría del Producto')['Precio'].sum().sort_values(ascending=False)

print("Ventas por categoría en Tienda 1:")
print(ventas_por_categoria_tienda1)
print("\nVentas por categoría en Tienda 2:")
print(ventas_por_categoria_tienda2)
print("\nVentas por categoría en Tienda 3:")
print(ventas_por_categoria_tienda3)
print("\nVentas por categoría en Tienda 4:")
print(ventas_por_categoria_tienda4)

# cantidad de productos vendidos por categoria
productos_por_categoria_tienda1 = tienda.groupby('Categoría del Producto').size().sort_values(ascending=False)
productos_por_categoria_tienda2 = tienda2.groupby('Categoría del Producto').size().sort_values(ascending=False)
productos_por_categoria_tienda3 = tienda3.groupby('Categoría del Producto').size().sort_values(ascending=False)
productos_por_categoria_tienda4 = tienda4.groupby('Categoría del Producto').size().sort_values(ascending=False)

print("\nNúmero de productos vendidos por categoría en Tienda 1:")
print(productos_por_categoria_tienda1)
print("\nNúmero de productos vendidos por categoría en Tienda 2:")
print(productos_por_categoria_tienda2)
print("\nNúmero de productos vendidos por categoría en Tienda 3:")
print(productos_por_categoria_tienda3)
print("\nNúmero de productos vendidos por categoría en Tienda 4:")
productos_por_categoria_tienda4

Ventas por categoría en Tienda 1:
Categoría del Producto
Electrónicos               429493500.0
Electrodomésticos          363685200.0
Muebles                    187633700.0
Instrumentos musicales      91299000.0
Deportes y diversión        39290000.0
Juguetes                    17995700.0
Artículos para el hogar     12698400.0
Libros                       8784900.0
Name: Precio, dtype: float64

Ventas por categoría en Tienda 2:
Categoría del Producto
Electrónicos               410831100.0
Electrodomésticos          348567800.0
Muebles                    176426300.0
Instrumentos musicales     104990300.0
Deportes y diversión        34744500.0
Juguetes                    15945400.0
Artículos para el hogar     14746900.0
Libros                      10091200.0
Name: Precio, dtype: float64

Ventas por categoría en Tienda 3:
Categoría del Producto
Electrónicos               410775800.0
Electrodomésticos          329237900.0
Muebles                    201072100.0
Instrumentos musicales      77380900.0
Deportes y diversión        35593100.0
Juguetes                    19401100.0
Artículos para el hogar     15060000.0
Libros                       9498700.0
Name: Precio, dtype: float64

Ventas por categoría en Tienda 4:
Categoría del Producto
Electrónicos               409476100.0
Electrodomésticos          283260200.0
Muebles                    192528900.0
Instrumentos musicales      75102400.0
Deportes y diversión        33350100.0
Juguetes                    20262200.0
Artículos para el hogar     15074500.0
Libros                       9321300.0
Name: Precio, dtype: float64

Número de productos vendidos por categoría en Tienda 1:
Categoría del Producto
Muebles                    465
Electrónicos               448
Juguetes                   324
Electrodomésticos          312
Deportes y diversión       284
Instrumentos musicales     182
Libros                     173
Artículos para el hogar    171
dtype: int64

Número de productos vendidos por categoría en Tienda 2:
Categoría del Producto
Muebles                    442
Electrónicos               422
Juguetes                   313
Electrodomésticos          305
Deportes y diversión       275
Instrumentos musicales     224
Libros                     197
Artículos para el hogar    181
dtype: int64

Número de productos vendidos por categoría en Tienda 3:
Categoría del Producto
Muebles                    499
Electrónicos               451
Juguetes                   315
Electrodomésticos          278
Deportes y diversión       277
Libros                     185
Artículos para el hogar    177
Instrumentos musicales     177
dtype: int64

Número de productos vendidos por categoría en Tienda 4:

Categoría del Producto
Muebles                    480
Electrónicos               451
Juguetes                   338
Deportes y diversión       277
Electrodomésticos          254
Artículos para el hogar    201
Libros                     187
Instrumentos musicales     170
dtype: int64

# 3. Calificación promedio de la tienda

# 4. Productos más y menos vendidos

# 5. Envío promedio por tienda

# Task
Analizar la facturación de cuatro tiendas a partir de sus respectivos DataFrames y mostrar el total facturado.

## Combinar dataframes

### Subtask:
Unir los DataFrames de las cuatro tiendas en un único DataFrame.

**Reasoning**:
Concatenate the four dataframes into a single dataframe and display the head of the new dataframe to verify the concatenation.